# uploadPath: /tmp/charts/upload
# templatePath: /tmp/charts/template
# snapPath: /tmp/charts/snap

helmRepos:
  - name: harbor
    url: https://192.168.0.188/chartrepo/chart
    caFile: E:/Projects/Go/helm-proxy/cert/ca.crt
    insecure_skip_tls_verify: false
    keyFile: E:/Projects/Go/helm-proxy/cert/ca.key
    password: Harbor12345
    username: admin
  - name: stable
    url: https://apphub.aliyuncs.com/stable
  - name: incubator
    url: https://apphub.aliyuncs.com/incubator
  - name: experimental
    url: https://apphub.aliyuncs.com/experimental