definitions:
  main.downFactor:
    properties:
      chartUrl:
        type: string
      repoUrl:
        type: string
    type: object
  main.releaseOptions:
    properties:
      atomic:
        type: boolean
      cleanup_on_fail:
        type: boolean
      create_namespace:
        description: only install
        type: boolean
      dependency_update:
        type: boolean
      description:
        type: string
      devel:
        type: boolean
      disable_hooks:
        type: boolean
      dry_run:
        description: common
        type: boolean
      force:
        description: only upgrade
        type: boolean
      install:
        type: boolean
      recreate:
        type: boolean
      set:
        items:
          type: string
        type: array
      set_string:
        items:
          type: string
        type: array
      skip_crds:
        type: boolean
      sub_notes:
        type: boolean
      timeout:
        type: string
      values:
        type: string
      wait:
        type: boolean
    type: object
  main.repoAddOptions:
    properties:
      caFile:
        type: string
      certFile:
        type: string
      insecureSkipTLSverify:
        type: boolean
      keyFile:
        type: string
      name:
        type: string
      noUpdate:
        type: boolean
      password:
        type: string
      url:
        type: string
      username:
        type: string
    type: object
  main.respBody:
    properties:
      code:
        description: 0 or 1, 0 is ok, 1 is error
        type: integer
      data:
        type: object
      error:
        type: string
    type: object
info:
  contact:
    email: mika055@163.com
    name: polya
  description: This is a api proxy of helm.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Helm API Proxy
  version: 0.0.1
paths:
  /charts:
    get:
      description: 根据chart名称，获取chart的readme、values、chart、template信息
      parameters:
      - description: chart名称
        in: query
        name: chart
        required: true
        type: string
      - description: chart版本
        in: query
        name: version
        type: string
      - description: Enums(all, readme, values, chart、template)
        in: query
        name: info
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.respBody'
      summary: 获取chart详细信息
      tags:
      - Chart
  /charts/export:
    post:
      description: helm pull
      parameters:
      - description: 带下载的chart路径信息
        in: body
        name: factor
        required: true
        schema:
          $ref: '#/definitions/main.downFactor'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.respBody'
      summary: 下载chart
      tags:
      - Chart
  /charts/template:
    post:
      description: 显示chart的k8s部署yaml，如果多个文件则合并到一个yaml一起展示出来
      parameters:
      - description: chart名称
        in: query
        name: chart
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.respBody'
      summary: 显示chart解析后的k8s部署yaml
      tags:
      - Chart
  /envs:
    get:
      description: 获取helm环境信息
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.respBody'
      summary: 获取helm环境信息
      tags:
      - Env
  /namespaces/{namespace}/releases:
    get:
      description: 根据命名空间获取release信息列表(helm list)
      parameters:
      - description: release所在k8s的命名空间
        in: path
        name: namespace
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.respBody'
      summary: 获取helm的release列表
      tags:
      - Release
  /namespaces/{namespace}/releases/{release}:
    delete:
      description: 卸载chart的实例(helm uninstall)
      parameters:
      - description: release所在k8s的命名空间
        in: path
        name: namespace
        required: true
        type: string
      - description: release名称
        in: path
        name: release
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.respBody'
      summary: 卸载release
      tags:
      - Release
    get:
      description: 根据名称获取release信息(helm get)
      parameters:
      - description: release所在k8s的命名空间
        in: path
        name: namespace
        required: true
        type: string
      - description: release名称
        in: path
        name: release
        required: true
        type: string
      - description: Enums(all, hooks, manifest, notes, values)
        in: query
        name: info
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.respBody'
      summary: 获取release详细信息
      tags:
      - Release
    post:
      description: 安装chart的实例(helm install)
      parameters:
      - description: release所在k8s的命名空间
        in: path
        name: namespace
        required: true
        type: string
      - description: release名称
        in: path
        name: release
        required: true
        type: string
      - description: chart名称
        in: query
        name: chart
        required: true
        type: string
      - description: 安装可选项
        in: body
        name: options
        required: true
        schema:
          $ref: '#/definitions/main.releaseOptions'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.respBody'
      summary: 安装release
      tags:
      - Release
  /namespaces/{namespace}/releases/{release}/histories:
    get:
      description: 获取release历史记录(helm release history)
      parameters:
      - description: release所在k8s的命名空间
        in: path
        name: namespace
        required: true
        type: string
      - description: release名称
        in: path
        name: release
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.respBody'
      summary: 查看release历史记录
      tags:
      - Release
  /namespaces/{namespace}/releases/{release}/status:
    get:
      description: 获取release状态信息(helm status)
      parameters:
      - description: release所在k8s的命名空间
        in: path
        name: namespace
        required: true
        type: string
      - description: release名称
        in: path
        name: release
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.respBody'
      summary: 查看release状态
      tags:
      - Release
  /repos:
    get:
      description: 列出所有repo
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.respBody'
      summary: 获取所有本地库
      tags:
      - Repository
  /repos/add:
    post:
      description: 通过名称，删除一个镜像库
      parameters:
      - description: 仓库信息
        in: body
        name: repoinfo
        required: true
        schema:
          $ref: '#/definitions/main.repoAddOptions'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.respBody'
      summary: 添加chart镜像库
      tags:
      - Repository
  /repos/charts:
    get:
      description: 在本地库中查找chart，如没有keyword则列出所有chart
      parameters:
      - description: 搜索关键字
        in: query
        name: keyword
        type: string
      - description: chart版本
        in: query
        name: version
        type: string
      - description: 如果true，查询出每个chart的所有版本；false，只列出每个chart最新版
        in: query
        name: versions
        type: boolean
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.respBody'
      summary: 查找chart/列出本地库中的所有chart
      tags:
      - Repository
  /repos/remove/{reponame}:
    delete:
      description: 通过名称，删除一个镜像库
      parameters:
      - description: repo1,repo2,repo3...
        in: path
        name: reponame
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.respBody'
      summary: 删除chart镜像库
      tags:
      - Repository
  /repos/update:
    put:
      description: 更新chart仓库信息
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.respBody'
      summary: 更新chart镜像库
      tags:
      - Repository
swagger: "2.0"
